name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Publish Windows
      run: dotnet publish -r win-x64 -c Release -p:Version=${GITHUB_REF_NAME#refs/tags/} --no-self-contained -o output/win-x64

    - name: Publish Linux
      run: dotnet publish -r linux-x64 -c Release -p:Version=${GITHUB_REF_NAME#refs/tags/} --no-self-contained -o output/linux-x64

    - name: Publish MacOS
      run: dotnet publish -r osx-x64 -c Release -p:Version=${GITHUB_REF_NAME#refs/tags/} --no-self-contained -o output/osx-x64

    - name: Rename MacOS file
      run: mv output/osx-x64/AzureDevOps.WikiPdfExport output/osx-x64/AzureDevOps.WikiPdfExport

    - name: Draft GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        generate_release_notes: true
        files: |
          output/win-x64/AzureDevOps.WikiPdfExport.exe
          output/win-x64/devopswikistyle.css
          output/win-x64/licenses.txt
          output/linux-x64/AzureDevOps.WikiPdfExport
          output/osx-x64/AzureDevOps.WikiPdfExport
